### PR TITLE
Replace dummy NusId with user inputted NusId

### PR DESCRIPTION
**Pull request by Rikko1204**

### CODE REVIEW

**Comment by Rikko1204** [comment]
Closes #45 #47

**Comment by hjuntan** [comment]
Add command is able to handle NusId and the nusid is now unique to each person in the address book

**Comment by hjuntan** [comment]
Sufficient unit testing are made for both `nusid` class and `addcommandparser`, however suggest that unit testing for `addcommand`, `UniquePersonList` and `parserutils` are modified; additional testing for `JsonAdaptedPersonTest`

**Comment by Rikko1204** [comment]
More test case added for ```JsonAdaptedPersonTest``` and ```ParserUtils```

**Comment by hjuntan** [comment]
Sufficient test cases are added, looks good to me; Pulling into branch.

**Pull request merged**
